### ISSUE TITLE
two methods don't work in 2020.10.7

### ISSUE THREAD

**Issue by akropivko** [aimeoscom/ai-payments#32]
Hi!
I've add "aimeos/ai-payments": "2020.10.7" to my composer 
and then have problems with two lines following:
$response->getTransactionId() //response nothing
and 
'clientIp' => $this->getValue( 'client.ipaddress' ) //response nothing

To force my app working I did replace these two lines with
$response->getRequest()->getTransactionId()
and 
'clientIp' => request()->ip() 

Probably is useful for you.
My composer info attached, if you need it.
[composer_info.txt](https://github.com/aimeoscom/ai-payments/files/6522359/composer_info.txt)

**Comment by aimeos** [comment]
This is specific to Laravel and can't be used everywhere else: `request()->ip()`. I think, we will have to change the interface of the process method to pass the request object instead of only the parameters to get the IP address.

Your workaround for Omnipay drivers not implementing `getTransactionId()` is now available in dev-master, 2021.07.x and 2020.10.x
